

USE QuanLyChuoiThoiTrang;
GO

-- ==================================================
-- RESET DATABASE STATE (DROPPING TABLES WITH RESPECT TO FK)
-- ==================================================
DROP TABLE IF EXISTS THONG_TIN_GIAO_HANG;
DROP TABLE IF EXISTS THANH_TOAN;
DROP TABLE IF EXISTS CHI_TIET_DON_HANG;
DROP TABLE IF EXISTS DON_HANG;
DROP TABLE IF EXISTS BIEN_THE_SAN_PHAM;
DROP TABLE IF EXISTS SAN_PHAM;
DROP TABLE IF EXISTS ANH_SAN_PHAM;
DROP TABLE IF EXISTS DANH_MUC;
DROP TABLE IF EXISTS KHACH_HANG;
DROP TABLE IF EXISTS CHUONG_TRINH_KHUYEN_MAI;
GO

-- ==================================================
-- CREATE TABLES (SCHEMA DEFINITION)
-- ==================================================

CREATE TABLE DANH_MUC (
    Ma_Danh_Muc INT IDENTITY(1,1) PRIMARY KEY,
    Ten_Danh_Muc NVARCHAR(255) NOT NULL
);

CREATE TABLE SAN_PHAM (
    Ma_San_Pham INT IDENTITY(1,1) PRIMARY KEY,
    Ten_San_Pham NVARCHAR(255) NOT NULL,
    Mo_Ta NVARCHAR(MAX),
    Chat_Lieu NVARCHAR(100),
    Ma_Danh_Muc INT,
    FOREIGN KEY (Ma_Danh_Muc) REFERENCES DANH_MUC(Ma_Danh_Muc) ON DELETE SET NULL
);

CREATE TABLE ANH_SAN_PHAM (
    Ma_Anh INT IDENTITY(1,1) PRIMARY KEY,
    Duong_Dan VARCHAR(255),
    Ma_San_Pham INT NOT NULL,
    FOREIGN KEY (Ma_San_Pham) REFERENCES SAN_PHAM(Ma_San_Pham) ON DELETE CASCADE
);

CREATE TABLE BIEN_THE_SAN_PHAM (
    Ma_Bien_The INT IDENTITY(1,1) PRIMARY KEY,
    Kich_Co NVARCHAR(50) NOT NULL,
    Mau_Sac NVARCHAR(50) NOT NULL,
    Gia_Niem_Yet INT NOT NULL,
    Ma_Vach_SKU VARCHAR(100) UNIQUE NOT NULL,
    So_Luong_Ton INT NOT NULL DEFAULT 0, -- Tồn kho quản lý tập trung tại đây
    Ma_San_Pham INT,
    FOREIGN KEY (Ma_San_Pham) REFERENCES SAN_PHAM(Ma_San_Pham) ON DELETE CASCADE
);

CREATE TABLE KHACH_HANG (
    Ma_Khach_Hang INT IDENTITY(1,1) PRIMARY KEY,
    Ho_Ten NVARCHAR(255) NOT NULL,
    So_Dien_Thoai VARCHAR(15) UNIQUE NOT NULL,
    Ngay_Sinh DATE,
    Hang_The NVARCHAR(50) DEFAULT N'Mới',
    Diem_Tich_Luy INT DEFAULT 0,
    Tong_Chi_Tieu INT DEFAULT 0
);

CREATE TABLE CHUONG_TRINH_KHUYEN_MAI (
    Ma_Giam_Gia VARCHAR(50) PRIMARY KEY,
    Mo_Ta NVARCHAR(MAX),
    Gia_Tri_Giam INT NOT NULL,
    Ngay_Bat_Dau DATE NOT NULL,
    Ngay_Ket_Thuc DATE NOT NULL,
    Don_Hang_Toi_Thieu INT DEFAULT 0
);

CREATE TABLE DON_HANG (
    Ma_Don_Hang INT IDENTITY(1,1) PRIMARY KEY,
    Ngay_Lap DATETIME2 DEFAULT GETDATE(),
    Tong_Tien INT NOT NULL DEFAULT 0,
    Trang_Thai NVARCHAR(100) DEFAULT N'Chờ xử lý',
    Ma_Khach_Hang INT,
    Ma_Giam_Gia VARCHAR(50),
    FOREIGN KEY (Ma_Khach_Hang) REFERENCES KHACH_HANG(Ma_Khach_Hang) ON DELETE SET NULL,
    FOREIGN KEY (Ma_Giam_Gia) REFERENCES CHUONG_TRINH_KHUYEN_MAI(Ma_Giam_Gia) ON DELETE SET NULL
);

CREATE TABLE CHI_TIET_DON_HANG (
    Ma_Chi_Tiet INT IDENTITY(1,1) PRIMARY KEY,
    So_Luong_Mua INT NOT NULL DEFAULT 1,
    Gia_Ap_Dung INT NOT NULL,
    Muc_Giam_Gia INT DEFAULT 0,
    Ma_Don_Hang INT,
    Ma_Bien_The INT,
    FOREIGN KEY (Ma_Don_Hang) REFERENCES DON_HANG(Ma_Don_Hang) ON DELETE CASCADE,
    FOREIGN KEY (Ma_Bien_The) REFERENCES BIEN_THE_SAN_PHAM(Ma_Bien_The) ON DELETE SET NULL
);

CREATE TABLE THANH_TOAN (
    Ma_Thanh_Toan INT IDENTITY(1,1) PRIMARY KEY,
    Phuong_Thuc NVARCHAR(100) NOT NULL, -- Tiền mặt, Chuyển khoản, Ví điện tử
    So_Tien INT NOT NULL,
    Ngay_Thanh_Toan DATETIME2 DEFAULT GETDATE(),
    Ma_Don_Hang INT,
    FOREIGN KEY (Ma_Don_Hang) REFERENCES DON_HANG(Ma_Don_Hang) ON DELETE CASCADE
);

CREATE TABLE THONG_TIN_GIAO_HANG (
    Ma_Giao_Hang INT IDENTITY(1,1) PRIMARY KEY,
    Don_Vi_Van_Chuyen NVARCHAR(255),
    Ma_Van_Don VARCHAR(100),
    Phi_Van_Chuyen INT DEFAULT 0,
    Dia_Chi_Giao NVARCHAR(500) NOT NULL,
    Ma_Don_Hang INT,
    FOREIGN KEY (Ma_Don_Hang) REFERENCES DON_HANG(Ma_Don_Hang) ON DELETE CASCADE
);
GO

